[theme]
primaryColor = "#D10A11"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F5F9"
textColor = "#1F2937"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
